// <auto-generated />
using System;
using MVC_EF.Exemplo1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MVC_EF.Exemplo1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MVC_EF.Exemplo1.Models.Autor", b =>
                {
                    b.Property<int>("AutorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AutorID"));

                    b.Property<DateTime?>("AutorDataNascimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("AutorEmail")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("AutorNome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("AutorID");

                    b.HasIndex("AutorNome");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("MVC_EF.Exemplo1.Models.AutorLivro", b =>
                {
                    b.Property<int>("AutorID")
                        .HasColumnType("integer");

                    b.Property<int>("LivroID")
                        .HasColumnType("integer");

                    b.Property<int>("OrdemAutoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("AutorID", "LivroID");

                    b.HasIndex("LivroID");

                    b.ToTable("AutoresLivro");
                });

            modelBuilder.Entity("MVC_EF.Exemplo1.Models.Editora", b =>
                {
                    b.Property<int>("EditoraID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EditoraID"));

                    b.Property<string>("EditoraCEP")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("EditoraCidade")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("EditoraComplemento")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("EditoraLogradouro")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("EditoraNome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("EditoraNumero")
                        .HasColumnType("integer");

                    b.Property<string>("EditoraPais")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("EditoraTelefone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("EditoraUF")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("EditoraID");

                    b.HasIndex("EditoraNome");

                    b.ToTable("Editoras");
                });

            modelBuilder.Entity("MVC_EF.Exemplo1.Models.Livro", b =>
                {
                    b.Property<int>("LivroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LivroID"));

                    b.Property<int>("EditoraID")
                        .HasColumnType("integer");

                    b.Property<int>("LivroAnoPublicacao")
                        .HasColumnType("integer");

                    b.Property<string>("LivroISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int>("LivroPaginas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("LivroTitulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("LivroID");

                    b.HasIndex("EditoraID");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("MVC_EF.Exemplo1.Models.OperacaoCompraVenda", b =>
                {
                    b.Property<int>("OperacaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OperacaoID"));

                    b.Property<int>("LivroID")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("OperacaoData")
                        .HasColumnType("date");

                    b.Property<short>("OperacaoQuantidade")
                        .HasColumnType("smallint");

                    b.HasKey("OperacaoID");

                    b.HasIndex("LivroID");

                    b.HasIndex("OperacaoData");

                    b.ToTable("Operacoes");
                });

            modelBuilder.Entity("MVC_EF.Exemplo1.Models.AutorLivro", b =>
                {
                    b.HasOne("MVC_EF.Exemplo1.Models.Autor", "Autor")
                        .WithMany("LivrosDoAutor")
                        .HasForeignKey("AutorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_EF.Exemplo1.Models.Livro", "Livro")
                        .WithMany("AutoresDoLivro")
                        .HasForeignKey("LivroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("MVC_EF.Exemplo1.Models.Livro", b =>
                {
                    b.HasOne("MVC_EF.Exemplo1.Models.Editora", "EditoraDoLivro")
                        .WithMany("LivrosDaEditora")
                        .HasForeignKey("EditoraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EditoraDoLivro");
                });

            modelBuilder.Entity("MVC_EF.Exemplo1.Models.OperacaoCompraVenda", b =>
                {
                    b.HasOne("MVC_EF.Exemplo1.Models.Livro", "LivroDaOperacao")
                        .WithMany("OperacoesDoLivro")
                        .HasForeignKey("LivroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LivroDaOperacao");
                });

            modelBuilder.Entity("MVC_EF.Exemplo1.Models.Autor", b =>
                {
                    b.Navigation("LivrosDoAutor");
                });

            modelBuilder.Entity("MVC_EF.Exemplo1.Models.Editora", b =>
                {
                    b.Navigation("LivrosDaEditora");
                });

            modelBuilder.Entity("MVC_EF.Exemplo1.Models.Livro", b =>
                {
                    b.Navigation("AutoresDoLivro");

                    b.Navigation("OperacoesDoLivro");
                });
#pragma warning restore 612, 618
        }
    }
}
